### ISSUE TITLE
Silex v2

### ISSUE THREAD

**Issue by Nekudapsik** [tommy-muehle/silex-sitemap-service-provider#3]
Is it suitable for silex v2?

**Comment by tommy-muehle** [comment]
I will check this tomorrow. If not, i'll be release a new version.

**Comment by tommy-muehle** [comment]
With a delay of one day I just released version 4.0 which supports Silex >= 2.0.
You can use it via
```
composer require tm/silex-sitemap-service-provider ^4.0
```
